import React, { useEffect, useState } from 'react';
import { useNav } from '../App';
import { useTheme, THEMES } from '../App';

export default function SettingsPage() {
  const { setPage, networkInfo } = useNav();
  const { themeName, changeTheme } = useTheme();

  const [defaultHost, setDefaultHost] = useState('');
  const [screenPort, setScreenPort] = useState('8080');
  const [controlPort, setControlPort] = useState('9999');
  const [savedMsg, setSavedMsg] = useState('');
  const [captureQuality, setCaptureQualityState] = useState('high');
  const [chatEnabled, setChatEnabledState] = useState(true);

  // Device identity — the ID is permanent (created once, on first run),
  // the password can be changed here to something that won't get
  // regenerated by "Generate New Password" on the Server page.
  const [deviceId, setDeviceId] = useState('');
  const [hostPassword, setHostPassword] = useState('');
  const [showHostPassword, setShowHostPassword] = useState(false);
  const [newHostPassword, setNewHostPassword] = useState('');
  const [passwordMsg, setPasswordMsg] = useState('');

  useEffect(() => {
    window.api?.get('lastHost').then(v => { if (v) setDefaultHost(v); });
    window.api?.get('lastScreenPort').then(v => { if (v) setScreenPort(v); });
    window.api?.get('lastControlPort').then(v => { if (v) setControlPort(v); });
    window.api?.get('captureQuality').then(v => { if (v) setCaptureQualityState(v); });
    window.api?.getChatDefault().then(v => setChatEnabledState(v !== false));
    window.api?.getDeviceId().then(res => {
      if (res?.ok) {
        setDeviceId(res.id);
        setHostPassword(res.password);
      }
    });
  }, []);

  const savePermanentPassword = async () => {
    const pw = newHostPassword.trim();
    if (!pw) return;
    const res = await window.api?.setHostPassword(pw);
    if (res?.ok) {
      setHostPassword(res.password);
      setNewHostPassword('');
      setPasswordMsg('Password updated — it will stay this way until changed here again.');
    } else {
      setPasswordMsg(res?.error || 'Could not update password');
    }
    setTimeout(() => setPasswordMsg(''), 3000);
  };

  const changeCaptureQuality = async (quality) => {
    setCaptureQualityState(quality); // optimistic
    const res = await window.api?.setCaptureQuality(quality);
    if (!res?.ok) {
      window.api?.get('captureQuality').then(v => setCaptureQualityState(v || 'high'));
    }
  };

  const toggleChatDefault = async (next) => {
    setChatEnabledState(next); // optimistic
    const res = await window.api?.setChatEnabled(next);
    if (!res?.ok) {
      window.api?.getChatDefault().then(v => setChatEnabledState(v !== false));
    }
  };

  const saveDefaults = async () => {
    await window.api?.set('lastHost', defaultHost);
    await window.api?.set('lastScreenPort', screenPort);
    await window.api?.set('lastControlPort', controlPort);
    setSavedMsg('Saved!');
    setTimeout(() => setSavedMsg(''), 2000);
  };

  return (
    <div className="app-body" style={{ overflow: 'hidden' }}>
      <div className="panel">
        <div className="sidebar">
          <div className="sidebar-header">
            <button className="back-btn" onClick={() => setPage('home')}>←</button>
            <div>
              <div className="sidebar-title">Settings</div>
              <div className="sidebar-sub">PREFERENCES</div>
            </div>
          </div>

          {networkInfo && (
            <div className="box">
              <div className="box-title">This Machine</div>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, lineHeight: 1.9 }}>
                <div style={{ color: 'var(--text-3)' }}>HOSTNAME</div>
                <div style={{ color: 'var(--accent)' }}>{networkInfo.hostname}</div>
                <div style={{ marginTop: 6, color: 'var(--text-3)' }}>PLATFORM</div>
                <div style={{ color: 'var(--accent-2)' }}>
                  {networkInfo.platform === 'linux' ? '🐧 Linux'
                    : networkInfo.platform === 'win32' ? '🪟 Windows'
                    : networkInfo.platform === 'darwin' ? '🍎 macOS'
                    : networkInfo.platform}
                </div>
                {networkInfo.ips?.length > 0 && (
                  <>
                    <div style={{ marginTop: 6, color: 'var(--text-3)' }}>LOCAL IPs</div>
                    {networkInfo.ips.map(ip => (
                      <div key={ip} style={{ color: 'var(--accent-2)' }}>{ip}</div>
                    ))}
                  </>
                )}
              </div>
            </div>
          )}

          <div className="mt-auto">
            <button className="btn btn-primary" onClick={saveDefaults}>
              {savedMsg || '✓ Save'}
            </button>
          </div>
        </div>

        <div className="panel-main settings-page">
          <div className="settings-wrap">

            {/* ── Theme Picker ── */}
            <div>
              <div className="settings-section-title">Appearance — Color Theme</div>
              <div className="theme-grid">
                {Object.entries(THEMES).map(([key, theme]) => (
                  <div
                    key={key}
                    className={`theme-swatch ${themeName === key ? 'active' : ''}`}
                    onClick={() => changeTheme(key)}
                  >
                    <span className="swatch-emoji">{theme.emoji}</span>
                    <span className="swatch-name">{theme.name}</span>
                  </div>
                ))}
              </div>

              <div style={{ marginTop: 14, padding: '12px 16px', background: 'var(--bg-2)', borderRadius: 'var(--r)', border: '1px solid var(--border)' }}>
                <div style={{ fontSize: 12, color: 'var(--text-2)', marginBottom: 6, fontFamily: 'var(--font-mono)' }}>
                  PREVIEW — <span style={{ color: 'var(--accent)' }}>{THEMES[themeName].name}</span>
                </div>
                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                  {['btn-primary', 'btn-success', 'btn-danger', 'btn-ghost'].map(cls => (
                    <button key={cls} className={`btn ${cls}`} style={{ width: 'auto', padding: '6px 14px', fontSize: 12 }}>
                      {cls.replace('btn-', '')}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* ── Screen Quality ── */}
            <div>
              <div className="settings-section-title">Screen Quality</div>
              <div style={{ display: 'flex', gap: 10 }}>
                {[
                  { key: 'low', label: 'Low', hint: 'more compression · faster' },
                  { key: 'medium', label: 'Medium', hint: 'balanced' },
                  { key: 'high', label: 'High', hint: 'sharp · default' },
                  { key: 'ultra', label: 'Ultra', hint: 'lossless PNG · sharpest text' },
                ].map(opt => (
                  <button
                    key={opt.key}
                    onClick={() => changeCaptureQuality(opt.key)}
                    className={`btn ${captureQuality === opt.key ? 'btn-primary' : 'btn-ghost'}`}
                    style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 2, padding: '10px 8px' }}
                  >
                    <span>{opt.label}</span>
                    <span style={{ fontSize: 9, opacity: 0.7, fontWeight: 400 }}>{opt.hint}</span>
                  </button>
                ))}
              </div>
              <div style={{ marginTop: 8, fontSize: 11, color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>
                Resolution is always captured at full native size — this only controls
                compression. Low/Medium/High use JPEG (smaller frames, some softening
                around edges/text). Ultra switches to lossless PNG — no compression
                artifacts at all, so text stays pixel-sharp, at the cost of larger
                frames. Takes effect immediately, even mid-session.
              </div>
            </div>

            {/* ── Chat ── */}
            <div>
              <div className="settings-section-title">Chat</div>
              <div style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                background: 'var(--bg-2)', border: '1px solid var(--border)',
                borderRadius: 'var(--r)', padding: '12px 16px',
              }}>
                <div>
                  <div style={{ fontSize: 13, color: 'var(--text-0)' }}>Allow chat with connected devices</div>
                  <div style={{ fontSize: 10, color: 'var(--text-3)', fontFamily: 'var(--font-mono)', marginTop: 3 }}>
                    {chatEnabled ? 'ENABLED — applies to future sessions' : 'DISABLED — applies to future sessions'}
                  </div>
                </div>
                <label className="switch" title={chatEnabled ? 'Disable chat' : 'Enable chat'}>
                  <input
                    type="checkbox"
                    checked={chatEnabled}
                    onChange={(e) => toggleChatDefault(e.target.checked)}
                  />
                  <span className="switch-slider" />
                </label>
              </div>
              <div style={{ marginTop: 8, fontSize: 11, color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>
                Sets the default chat state a hosted session starts with, and — if you're
                currently hosting — flips it for that session too, same as the switch
                inside the Chat panel on the Server page. Chat is available to any
                device that's paired and connected, regardless of whether it holds
                remote control.
              </div>
            </div>

            {/* ── Device Identity & Password ── */}
            <div>
              <div className="settings-section-title">Device Identity &amp; Password</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                <div className="field">
                  <label className="field-label">Device ID (permanent)</label>
                  <div style={{
                    fontFamily: 'var(--font-mono)', fontSize: 14, letterSpacing: '0.05em',
                    color: 'var(--accent)', background: 'var(--bg-2)', border: '1px solid var(--border)',
                    borderRadius: 'var(--r)', padding: '9px 12px',
                  }}>
                    {deviceId || '—'}
                  </div>
                  <div style={{ fontSize: 10, color: 'var(--text-3)', fontFamily: 'var(--font-mono)', marginTop: 4 }}>
                    Generated once on first run and never changes.
                  </div>
                </div>

                <div className="field">
                  <label className="field-label">Current Password</label>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <div style={{
                      flex: 1, fontFamily: 'var(--font-mono)', fontSize: 14, letterSpacing: '0.05em',
                      color: 'var(--accent-2)', background: 'var(--bg-2)', border: '1px solid var(--border)',
                      borderRadius: 'var(--r)', padding: '9px 12px',
                    }}>
                      {hostPassword ? (showHostPassword ? hostPassword : '•'.repeat(hostPassword.length)) : '—'}
                    </div>
                    <button className="btn btn-ghost" style={{ width: 'auto', padding: '0 14px' }} onClick={() => setShowHostPassword(s => !s)}>
                      {showHostPassword ? 'Hide' : 'Show'}
                    </button>
                  </div>
                </div>

                <div className="field">
                  <label className="field-label">Set a Permanent Password</label>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <input
                      className="field-input"
                      placeholder="Enter a new password"
                      value={newHostPassword}
                      onChange={e => setNewHostPassword(e.target.value)}
                      onKeyDown={e => e.key === 'Enter' && savePermanentPassword()}
                    />
                    <button className="btn btn-primary" style={{ width: 'auto', padding: '0 16px' }} onClick={savePermanentPassword}>
                      Save
                    </button>
                  </div>
                  <div style={{ fontSize: 10, color: 'var(--text-3)', fontFamily: 'var(--font-mono)', marginTop: 4 }}>
                    Unlike "Generate New Password" on the Server page, this password
                    stays fixed across sessions and restarts until you change it here.
                    Applies immediately if you're currently hosting.
                  </div>
                  {passwordMsg && (
                    <div style={{ fontSize: 11, color: 'var(--accent-2)', fontFamily: 'var(--font-mono)', marginTop: 4 }}>
                      {passwordMsg}
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* ── Connection Defaults ── */}
            <div>
              <div className="settings-section-title">Connection Defaults</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                <div className="field">
                  <label className="field-label">Default Server Host</label>
                  <input
                    className="field-input"
                    placeholder="192.168.1.100"
                    value={defaultHost}
                    onChange={e => setDefaultHost(e.target.value)}
                  />
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
                  <div className="field">
                    <label className="field-label">Screen Port</label>
                    <input className="field-input" value={screenPort} onChange={e => setScreenPort(e.target.value)} />
                  </div>
                  <div className="field">
                    <label className="field-label">Control Port</label>
                    <input className="field-input" value={controlPort} onChange={e => setControlPort(e.target.value)} />
                  </div>
                </div>
              </div>
            </div>

            {/* ── Server Setup ── */}
            <div>
              <div className="settings-section-title">Python Server Setup</div>
              <div style={{ background: 'var(--bg-2)', border: '1px solid var(--border)', borderRadius: 'var(--r)', padding: 16, fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-2)', lineHeight: 2 }}>
                <div style={{ color: 'var(--text-3)', marginBottom: 8 }}>INSTALL DEPENDENCIES</div>
                <div style={{ background: 'var(--bg-base)', border: '1px solid var(--border)', borderRadius: 6, padding: '8px 12px', color: 'var(--accent-2)' }}>
                  pip install -r requirements.txt
                </div>
                <div style={{ color: 'var(--text-3)', margin: '10px 0 8px' }}>LINUX EXTRAS (X11)</div>
                <div style={{ background: 'var(--bg-base)', border: '1px solid var(--border)', borderRadius: 6, padding: '8px 12px', color: 'var(--accent)' }}>
                  sudo apt install xdotool
                </div>
                <div style={{ color: 'var(--text-3)', margin: '10px 0 8px' }}>LINUX EXTRAS (WAYLAND)</div>
                <div style={{ background: 'var(--bg-base)', border: '1px solid var(--border)', borderRadius: 6, padding: '8px 12px', color: 'var(--accent)' }}>
                  sudo apt install ydotool<br />
                  sudo systemctl enable --now ydotoold
                </div>
              </div>
            </div>

            {/* ── About ── */}
            <div>
              <div className="settings-section-title">About</div>
              <div style={{ background: 'var(--bg-2)', border: '1px solid var(--border)', borderRadius: 'var(--r)', padding: 16, fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-2)', lineHeight: 1.9 }}>
                <div><span style={{ color: 'var(--accent)' }}>TouchBridge</span> v1.0.0</div>
                <div>Electron + React + Python backend</div>
                <div>TCP sockets: port 8080 (screen) + 9999 (control)</div>
                <div style={{ color: 'var(--text-3)' }}>Linux (X11/Wayland) · Windows · macOS</div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}